### ISSUE TITLE
Uncountable string singular issue

### ISSUE THREAD

**Issue by TryYQ** [blakeembrey/pluralize#132]
When I try to make 'research series' singular, I get 'research sery' but the right string also is 'research series'. 
I know I can add a rule to avoid this, but it means I must add many rules if I will use other uncountable string like 'your homework'.
Is this a known issue? 
Could you help to give me some advice? Thanks in advance.

**Comment by blakeembrey** [comment]
This library works on words, not phrases.

**Comment by blakeembrey** [comment]
For example, series is defined here as a word: https://github.com/blakeembrey/pluralize/blob/abb399111aedd1d62dd418d7e0217d85f5bf22c9/pluralize.js#L473. If you wish to make it a match trailing strings it must be turned into a regex instead. Unfortunately none of this library is really designed for multiple word though (and arguably shouldn't be) since it gets trickier, so passing just the word you want to pluralize is the best course of action. 

If you wish to write a proposal to support phrases, feel free to create an issue for that!
