### ISSUE TITLE
pluralize('is', 1) yields 'i'?

### ISSUE THREAD

**Issue by dontmitch** [blakeembrey/pluralize#28]
```js
pluralize('is', 0) === 'is'
pluralize('is', 1) === 'i'
pluralize('is', 2) === 'is'

pluralize.addIrregularRule('is', 'are')

// Expected behavior...
pluralize('is', 0) === 'are'
pluralize('is', 1) === 'is'
pluralize('is', 2) === 'are'
```

I'm most confused by the `pluralize('is', 1) === 'i'` case. Before adding the irregular case, my expectation is that pluralize wouldn't mutate the word...

**Comment by blakeembrey** [comment]
@dontmitch Pluralize is based on regular expressions, not a dictionary. The final fallback for singularization is to remove the trailing `s`. Of course, for other words this is caught before you reach there. Since it mostly handles nouns and other odd cases that have come up, this just hasn't been handled. It's easy enough to add this rule, as you did, and I think it is a valid rule to have.

**Comment by dontmitch** [comment]
Ahh, that explains it. Fair enough, just figured I'd pass that along. :+1:
