### ISSUE TITLE
Which direction (pluralize, or singularize?) is easier, or less ambiguous?

### ISSUE THREAD

**Issue by GitTom** [blakeembrey/pluralize#45]
I'm going to use the pluralize module to convert a big list of words - all singular, or all plural - into a list that contains both the singular & the plural of each.

Am I better to start from a list of singular words or plural words?

**Comment by blakeembrey** [comment]
Should be fine either way, I wouldn't really be able to answer it because if one was performing worse I'd look at fixing it. For consistency sakes, I'd probably start with singular anyway and go to a plural. Remember that this module is only a light-weight modules for working with English using RegExps. If you want complete plural support (less chance of issues) you might want to use a dictionary.

**Comment by GitTom** [comment]
Ok, thanks for the response.
