### ISSUE TITLE
SemVer compliance

### ISSUE THREAD

**Issue by maschwenk** [blakeembrey/pluralize#72]
Hey!

Thanks for writing this module. I've seen it used in a lot of my own projects and others. One thing I've noticed is that you seem to be incrementing the major version of the module even when the changes are backwards compatible. The guideline for SemVer is defined here: http://semver.org/ and it states:

> 
> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API. It MUST be incremented if any public API functionality is marked as deprecated. It MAY be incremented if substantial new functionality or improvements are introduced within the private code. It MAY include patch level changes. Patch version MUST be reset to 0 when minor version is incremented.
> 
> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API. It MAY include minor and patch level changes. Patch and minor version MUST be reset to 0 when major version is incremented.

Most changesets in this project do not appear to fall into the _major_ category. For open source projects keeping their NPM packages up to date with things like Greenkeeper, these major releases create a lot of noise for a package for which most projects would not need to rapidly update.

Thanks so much for your work on this project and have a great week!

Thanks,
Max

**Comment by blakeembrey** [comment]
Any change to a pluralization is most definitely a major change. If this is used by a database and happens to use a word that has now change, it has broken their project. I'm going to keep using major versions for this reason, I'm not sure that I should do minor or patches lest it be used in a situation where it's assumed the change won't break for anyone.

**Comment by blakeembrey** [comment]
> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API

The words are part of the public API, and the word changes are backward incompatible.

**Comment by blakeembrey** [comment]
I'm going to close the issue, but feel free to continue the discussion. I would love to have more data. Since the words are part of the public API and any pluralization change can break a dependency (imagine deploying an update to your server and because of a plural change your app is broken - in the case of ODM or auto-generated servers) I'm going to continue with major version changes (as defined by semver). If you disagree, feel free to lay out your arguments here - it's definitely not the end of the conversation.

Even things as innocuous as TypeScript interface generation that may be using a word that was changed in a major release, resulting in application compilation breaking.

**Comment by maschwenk** [comment]
After I opened issue I thought about it more and came to a similar conclusion. 

The most obvious comparison I can think of is ActiveSupport in Rails. If pluralization rules changed there, your application could start referencing differently named tables and therefore it is definitely a breaking change. I'll circle around if I find a good example in the ActiveSupport changelogs.

Thanks for the thoughtful response.
